export const colleges = [
  "B V Raju Institute of Technology",
  "Chaitanya Bharathi Institute of Technology",
  "College of Engineering, Osmania University",
  "GITAM Institute of Technology, Hyderabad Campus",
  "ICFAI Foundation for Higher Education (ICFAI Tech)",
  "Indian Institute of Information Technology Hyderabad",
  "Indian Institute of Technology Hyderabad",
  "Jawaharlal Nehru Technological University Hyderabad",
  "K L University (K L College of Engineering)",
  "National Institute of Technology Warangal",
  "Sree Vidyanikethan Engineering College",
  "Sreenidhi Institute of Science and Technology",
  "VIT-AP University",
  "Acharya Nagarjuna University College of Engineering",
  "Aditya Engineering College",
  "Anil Neerukonda Institute of Technology and Sciences",
  "CVR College of Engineering",
  "GMR Institute of Technology",
  "Gayatri Vidya Parishad College of Engineering",
  "JNTU Kakinada (Jawaharlal Nehru Technological University Kakinada)",
  "JNTU Anantapur (Jawaharlal Nehru Technological University Anantapur)",
  "Kakatiya Institute of Technology and Science, Warangal",
  "Koneru Lakshmaiah Education Foundation (K L Deemed to be University \u2013 Main Campus)",
  "Malla Reddy Engineering College",
  "Mahatma Gandhi Institute of Technology",
  "SRKR Engineering College",
  "Vasavi College of Engineering",
  "VNR Vignana Jyothi Institute of Engineering and Technology",
];
