export const colleges = [
  "Achutha Institute of Technology",
  "Adichunchanagiri Institute of Technology",
  "AGM Rural Engineering College",
  "AJ Institute of Engineering and Technology",
  "Akash Institute of Engineering and Technology",
  "Akshaya Institute of Technology",
  "Alliance University (College of Engineering)",
  "Alva's Institute of Engineering and Technology",
  "Alpha College of Engineering",
  "AMC Engineering College",
  "Amrita School of Engineering, Bengaluru",
  "Amrutha Institute of Engineering and Management Sciences",
  "Anjuman Engineering College",
  "Appa Institute of Engineering and Technology",
  "ATME College of Engineering",
  "Atria Institute of Technology",
  "Bahubali College of Engineering",
  "Ballari Institute of Technology & Management",
  "Bangalore College of Engineering and Technology",
  "Bangalore Institute of Technology",
  "Bangalore Technological Institute",
  "Basava Kalyan Engineering College",
  "Bearys Institute of Technology",
  "BGS Institute of Technology",
  "BMS College of Engineering",
  "BMS Institute of Technology & Management",
  "BNM Institute of Technology",
  "Brindavan College of Engineering",
  "BTL Institute of Technology and Management",
  "C. Byregowda Institute of Technology",
  "Cambridge Institute of Technology",
  "Cambridge Institute of Technology North Campus",
  "Canara Engineering College",
  "Cauvery Institute of Technology",
  "Channabasaveshwara Institute of Technology",
  "Christ University (Faculty of Engineering)",
  "City Engineering College",
  "CMR Institute of Technology",
  "Dayananda Sagar Academy of Technology and Management",
  "Dayananda Sagar College of Engineering",
  "Don Bosco Institute of Technology",
  "Dr. Ambedkar Institute of Technology",
  "Dr. Sri Sri Sri Shivakumara Mahaswamy College of Engineering",
  "Dr. T. Thimmaiah Institute of Technology",
  "East Point College of Engineering and Technology",
  "East West Institute of Technology",
  "Ekalavya Institute of Technology",
  "G Madegowda Institute of Technology",
  "Ghousia College of Engineering",
  "Global Academy of Technology",
  "Gogte Institute of Technology",
  "Government Engineering College, Ballari",
  "Government Engineering College, Chamarajanagar",
  "Government Engineering College, Hassan",
  "Government Engineering College, K.R. Pet",
  "Government Engineering College, Koppal",
  "Government Engineering College, Kushalnagar",
  "Government Engineering College, Raichur",
  "GSSS Institute of Engineering and Technology for Women",
  "Gurunanak Dev Engineering College, Bidar",
  "HKBK College of Engineering",
  "HMS Institute of Technology",
  "Impact College of Engineering and Applied Sciences",
  "Indian Institute of Information Technology, Bengaluru",
  "Indian Institute of Information Technology, Dharwad",
  "Indian Institute of Science (Engineering Departments)",
  "Indian Institute of Technology Dharwad",
  "Islamiah Institute of Technology",
  "Jain College of Engineering",
  "Jawaharlal Nehru National College of Engineering",
  "Jnana Vikas Institute of Technology",
  "JSS Academy of Technical Education, Bengaluru",
  "Jyothy Institute of Technology",
  "KCT Engineering College",
  "KLE Dr. M.S. Sheshgiri College of Engineering and Technology",
  "KLE Institute of Technology",
  "KLE Technological University",
  "KLS Vishwanathrao Deshpande Institute of Technology",
  "Lingaraj Appa Engineering College",
  "M.S. Ramaiah Institute of Technology",
  "M.S. Ramaiah University of Applied Sciences (Engineering)",
  "Maharaja Institute of Technology, Mysore",
  "Malnad College of Engineering",
  "Manipal Institute of Technology",
  "Mangalore Institute of Technology & Engineering",
  "Maratha Mandal Engineering College",
  "Moodlakatte Institute of Technology",
  "MVJ College of Engineering",
  "Mysuru Royal Institute of Technology",
  "Nagarjuna College of Engineering and Technology",
  "National Institute of Engineering, Mysuru",
  "National Institute of Technology Karnataka",
  "New Horizon College of Engineering",
  "NIE Institute of Technology",
  "Nitte Mahalinga Adyanthaya Memorial Institute of Technology",
  "Nitte Meenakshi Institute of Technology",
  "P.A. College of Engineering",
  "PDA College of Engineering",
  "PES College of Engineering, Mandya",
  "PES Institute of Technology and Management",
  "PES University (Engineering)",
  "PNS Institute of Technology",
  "Proudadevaraya Institute of Technology",
  "R.V. College of Engineering",
  "R.V. Institute of Technology and Management",
  "RajaRajeswari College of Engineering",
  "Rajeev Institute of Technology",
  "RNS Institute of Technology",
  "Rashtreeya Vidyalaya College of Engineering",
  "Reva University (Engineering)",
  "Rural Engineering College, Gadag",
  "Sai Vidya Institute of Technology",
  "Sahyadri College of Engineering and Management",
  "Sampoorna Institute of Technology and Research",
  "Sapthagiri College of Engineering",
  "SCT Institute of Technology",
  "SDM College of Engineering and Technology",
  "SDM Institute of Technology, Ujire",
  "Shaikh College of Engineering and Technology",
  "Shah-Shib College of Engineering",
  "Shree Devi Institute of Technology",
  "Shree Vinayaka Institute of Technology",
  "Shri Madhwa Vadiraja Institute of Technology and Management",
  "Siddaganga Institute of Technology",
  "Sir M. Visvesvaraya Institute of Technology",
  "SJB Institute of Technology",
  "SJC Institute of Technology",
  "Sri Basaveshwara Institute of Technology",
  "Sri Dharmasthala Manjunatheshwara College of Engineering and Technology",
  "Sri Jayachamarajendra College of Engineering",
  "Sri Krishna Institute of Technology",
  "Sri Revana Siddeshwara Institute of Technology",
  "Sri Sairam College of Engineering",
  "Sri Siddhartha Institute of Technology",
  "Sri Venkateshwara College of Engineering",
  "Srinivas Institute of Technology",
  "St. Joseph Engineering College",
  "T. John Institute of Technology",
  "The Oxford College of Engineering",
  "University BDT College of Engineering",
  "University Visvesvaraya College of Engineering",
  "V.S.M. Institute of Technology",
  "Veerappa Nisty Engineering College",
  "Vidya Vardhaka College of Engineering",
  "Vidya Vikas Institute of Engineering and Technology",
  "Vijaya Vittala Institute of Technology",
  "Vivekananda College of Engineering and Technology",
  "Vivekananda Institute of Technology",
  "Yellamma Dasappa Institute of Technology",
  "Yenepoya Institute of Technology",
];
