export const colleges = [
    "APJ Abdul Kalam Technological University",
    "College of Engineering Attingal",
    "College of Engineering Karunagappally",
    "College of Engineering Munnar",
    "College of Engineering Thiruvananthapuram",
    "Cochin University of Science and Technology",
    "Government College of Engineering Kannur",
    "Government Engineering College Barton Hill",
    "Government Engineering College Kozhikode",
    "Government Engineering College Thrissur",
    "Indian Institute of Information Technology Kottayam",
    "Indian Institute of Space Science and Technology",
    "Indian Institute of Technology Palakkad",
    "Mar Athanasius College of Engineering",
    "MES College of Engineering",
    "National Institute of Technology Calicut",
    "NSS College of Engineering",
    "Rajiv Gandhi Institute of Technology, Kottayam",
    "Saintgits College of Engineering",
    "Sahrdaya College of Engineering and Technology",
    "SCMS School of Engineering and Technology",
    "Thangal Kunju Musaliar College of Engineering",
    "TKM Institute of Technology",
    "Vidya Academy of Science and Technology"
];
