export const colleges = [
  "Bharati Vidyapeeth College of Engineering, Pune",
  "College of Engineering Pune (COEP Technological University)",
  "Dr. D. Y. Patil Institute of Technology, Pimpri",
  "Dwarkadas J. Sanghvi College of Engineering",
  "GH Raisoni College of Engineering, Nagpur",
  "Indian Institute of Information Technology Nagpur",
  "Indian Institute of Technology Bombay",
  "Institute of Chemical Technology, Mumbai",
  "K J Somaiya College of Engineering",
  "Laxminarayan Institute of Technology, Nagpur",
  "MIT World Peace University, Pune",
  "Ramrao Adik Institute of Technology",
  "Rajarshi Shahu College of Engineering, Pune",
  "Sardar Patel Institute of Technology",
  "Veermata Jijabai Technological Institute, Mumbai",
  "Visvesvaraya National Institute of Technology, Nagpur",
  "Vishwakarma Institute of Information Technology, Pune",
  "Walchand College of Engineering, Sangli",
  "Yeshwantrao Chavan College of Engineering, Nagpur",
  "AISSMS College of Engineering, Pune",
  "Atharva College of Engineering, Mumbai",
  "Bajaj Institute of Technology, Wardha",
  "Bharati Vidyapeeth Deemed University College of Engineering, Pune",
  "Cummins College of Engineering for Women, Pune",
  "D Y Patil College of Engineering, Akurdi",
  "Datta Meghe College of Engineering, Navi Mumbai",
  "Don Bosco Institute of Technology, Mumbai",
  "Fr. Conceicao Rodrigues College of Engineering",
  "Fr. Conceicao Rodrigues Institute of Technology, Vashi",
  "Government College of Engineering, Amravati",
  "Government College of Engineering, Aurangabad",
  "Government College of Engineering, Jalgaon",
  "Government College of Engineering, Karad",
  "Government College of Engineering, Nagpur",
  "Government College of Engineering, Yavatmal",
  "JSPM Narhe Technical Campus, Pune",
  "K K Wagh Institute of Engineering Education and Research, Nashik",
  "Lokmanya Tilak College of Engineering, Navi Mumbai",
  "Mahatma Gandhi Mission's College of Engineering, Navi Mumbai",
  "Marathwada Institute of Technology, Aurangabad",
  "Modern College of Engineering, Pune",
  "Mumbai University Institute of Chemical Technology (UICT)",
  "NBN Sinhgad School of Engineering, Pune",
  "Pimpri Chinchwad College of Engineering",
  "Pune Institute of Computer Technology (PICT)",
  "Rajiv Gandhi Institute of Technology, Mumbai",
  "RCOEM \u2013 Shri Ramdeobaba College of Engineering and Management",
  "Shah and Anchor Kutchhi Engineering College",
  "Shivaji University College of Engineering",
  "Sinhgad College of Engineering, Pune",
  "Sipna College of Engineering and Technology",
  "Smt. Indira Gandhi College of Engineering, Navi Mumbai",
  "St. Francis Institute of Technology, Mumbai",
  "Thadomal Shahani Engineering College",
  "Universal College of Engineering, Vasai",
  "Vasantdada Patil Pratishthan\u2019s College of Engineering",
  "Vidyalankar Institute of Technology",
  "Vivekanand Education Society\u2019s Institute of Technology",
  "ZCOER \u2013 Zeal College of Engineering and Research",
];
