export const colleges = [
    "National Institute of Technology Tiruchirappalli",
    "Vellore Institute of Technology, Vellore",
    "SRM Institute of Science and Technology, Chennai",
    "SASTRA Deemed University, Thanjavur",
    "Kalasalingam Academy of Research and Education",
    "Sri Sivasubramaniya Nadar College of Engineering",
    "PSG College of Technology",
    "Sreepathy Institute of Management and Technology",
    "Sathyabama Institute of Science and Technology",
    "Sri Krishna College of Engineering and Technology",
    "Rajalakshmi Engineering College",
    "Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology",
    "Thiagarajar College of Engineering",
    "Indian Institute of Information Technology Design and Manufacturing Kancheepuram",
    "KPR Institute of Engineering and Technology",
    "Anna University, Chennai",
    "College of Engineering, Guindy (Anna University)",
    "Alagappa Chettiar College of Engineering and Technology",
    "Bannari Amman Institute of Technology",
    "Chennai Institute of Technology",
    "Coimbatore Institute of Technology",
    "Dr. Mahalingam College of Engineering and Technology",
    "Easwari Engineering College",
    "Government College of Engineering, Salem",
    "Government College of Engineering, Tirunelveli",
    "Hindustan Institute of Technology and Science",
    "Jeppiaar Engineering College",
    "Kongu Engineering College",
    "Kumaraguru College of Technology",
    "Madras Institute of Technology (Anna University)",
    "Mepco Schlenk Engineering College",
    "Panimalar Engineering College",
    "RMK Engineering College",
    "RMK College of Engineering and Technology",
    "Saveetha Engineering College",
    "Sri Eshwar College of Engineering",
    "Sri Ramakrishna Engineering College",
    "St. Joseph\u2019s College of Engineering, Chennai",
    "Velammal Engineering College",
    "Velammal Institute of Technology"
];
